### ISSUE TITLE
Panel at bottom misaligns showing bookmark

### ISSUE THREAD

**Issue by Skrell** [Dook1/Bookmarks-Dook#20] opened 2022-11-08 19:02 UTC
When I click on a bookmark in the panel at the bottom of NPP, it doesn't bring the bookmark into view, instead it offsets it by several lines which I'm guessing are the height of the panel itself.   In other words, the panel's height shouldn't affect where the bookmark is displayed on the screen when clicked.

**Comment by Dook1** [comment] 2022-11-08 20:10
I can't reproduce it.  Attach a video.

**Comment by Dook1** [comment] 2022-11-12 00:04
possibly fixed in v3.1

**Closed as completed** 2022-11-29 01:45 UTC
