### ISSUE TITLE
plugin source code

### ISSUE THREAD

**Issue by darkworks** [Dook1/Bookmarks-Dook#16] opened 2022-08-15 11:00 UTC
Hi
can we have access to plugin source code so that can modify it according to needs

thanks

**Comment by Dook1** [comment] 2022-08-15 18:28
Sorry, no.

**Comment by darkworks** [comment] 2022-08-16 10:08
![image](https://user-images.githubusercontent.com/12841788/184854105-4b7ebd53-a4ba-49d7-b063-5cba016b6616.png)

so can u please add table like style to the bookmark panel , two columns one so that keep code line and another line where user can click and add comment for the bookmark line.  currently when double click bookmark  it select code line is removed if type anything or you have to manually scroll ahead to line for comment

thanks

**Comment by Dook1** [comment] 2022-08-16 10:17
Ok. I'll do it a little later.

**Comment by darkworks** [comment] 2022-08-16 10:25
+ also table Striped rows  will be good , as with different rows colors eyes are comfortable as we have in bootstrap

![image](https://user-images.githubusercontent.com/12841788/184857543-0c85678e-c50a-489c-beb7-9bd36bfeed9a.png)

thanks

**Comment by Dook1** [comment] 2022-08-16 10:41
ok

**Comment by darkworks** [comment] 2022-08-16 16:56
+ also if possible please add  Search field to the panel too so that user can search via bookmarks , search through comments will be good incase comment is not there then search in code for matching keyword  , with search and clear button. Clear button should clear search so that all bookmarks are displayed incase of search only matching bookmarks display

![image](https://user-images.githubusercontent.com/12841788/184935885-e5133f9f-5e97-443d-8eaa-95c7d7a64117.png)

thanks

**Comment by Dook1** [comment] 2022-08-16 17:03
The search function is already there. I don't see the point in a separate search bar. Moreover, it is not easy to place the component in the window header.

**Comment by darkworks** [comment] 2022-08-16 17:17
hmmmm i was talking about search function in bookmarksDook panel , i not see any search field in bookmark panel or is there any other way to search among bookmarks . normally i work in big files where i have 20 plus bookmarks and mostly i have to scroll down in bookmarks panel to find desire bookmark. that's why i thought search field n bookmarks panel will be good idea.

**Comment by Dook1** [comment] 2022-08-16 17:28
Focus the Bookmarks@Dook panel and type the desired text.

**Comment by darkworks** [comment] 2022-08-16 17:28
+ one another idea currently the bookmarks are push too much to left . so i think it will be good to push it a bit right like notepad++ editor window

**current**
![image](https://user-images.githubusercontent.com/12841788/184940752-05681320-71d2-42c6-b36d-d86e0bf76c0b.png)

**beauty**
![image](https://user-images.githubusercontent.com/12841788/184941292-233c6d70-be7e-4cee-8683-76655a3f7d4e.png)

so as we discussed above about adding table rows so i think it will be good to display it like proper table with each bookmark it start add line number more like table ID , however these line number it start of bookmark may need update time to time because line numbers can change as code in editor when increase or decrease.

thanks

**Comment by Dook1** [comment] 2022-08-16 17:40
1) Focus the Bookmarks@Dook panel and type the desired text.
2) The line number is already in the current version. I won't adjust its color to NPP+.
3) The indents can wait.

**Comment by gskoczylas** [comment] 2022-08-29 08:57
Could you add an option to cause all bookmarks from all open files to be shown, not just the current file?

**Comment by Dook1** [comment] 2022-08-29 10:07
Yes

**Comment by darkworks** [comment] 2022-09-29 11:38
sir any update on the changes implementation we discussed.

**Comment by Dook1** [comment] 2022-09-29 17:45
I plan to do it next week if I have free time.

**Comment by Dook1** [comment] 2022-10-26 14:10
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

**Comment by darkworks** [comment] 2022-10-27 17:35
> https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

thanks for the amazing work . the new v3.0 looks lovey.
can you please tell how to add notes what is short cut ?

**Comment by Dook1** [comment] 2022-10-27 19:43
Long click on "Note" cell or Ctrl-Alt-F6 or Plugins->Bookmarks@Dook->Rename bookmark

**Comment by darkworks** [comment] 2022-11-04 10:52
@Dook1 sir there are some bug in the new version . old version was ok in jumping in even jumping to lines in large files . however new version cant jump to bookmarks correctly. pls check the video i have attached.

some screenshots  upon clicking bookmarks
![image](https://user-images.githubusercontent.com/12841788/199955422-8b216a11-5275-484a-8fcf-9ee3eb229c47.png)

![image](https://user-images.githubusercontent.com/12841788/199955456-630497e1-0ec8-4e57-a914-4cc4cb5e1e2e.png)
![image](https://user-images.githubusercontent.com/12841788/199955806-a137fbfa-a584-4433-a95e-0de450ac97ea.png)


[notePad_test.zip](https://github.com/Dook1/Bookmarks-Dook/files/9937459/notePad_test.zip)

note pad v 8.4.6 64 bit windows

**Comment by Dook1** [comment] 2022-11-04 11:19
I can't reproduce this myself.  Try to download again.  Maybe the bug has already been fixed.
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

**Comment by darkworks** [comment] 2022-11-23 06:41
> I can't reproduce this myself. Try to download again. Maybe the bug has already been fixed. https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

thanks seems like you fixed it in v3.1 :)

**Comment by darkworks** [comment] 2022-11-23 06:45
however there is one issue if notepad++ is installed in Program Files like : C:\Program Files\Notepad++\plugins\BookmarksDook\lv.ini

looks like plugin have no proper access to  `lv.ini` file and sometime it would trigger access denied type error when working in notepad in bookmark panel. 
![image](https://user-images.githubusercontent.com/12841788/203486397-1a6a3296-f1c1-423e-a481-a862acb947f9.png)

try to click on the `Text column it will trigger that access denied error. so i suggest keep that lv.ini in appdata somewhere in notepadd++ appdata directory instead of program files plugin folder
![image](https://user-images.githubusercontent.com/12841788/203486471-07147daa-7088-482a-a5a0-fe39627a99a1.png)

**Comment by Dook1** [comment] 2022-11-29 01:51
Fixed in 3.1.1
Zebra added in 3.1.1
Other proposals rejected.

**Closed as completed by Dook1** 2022-11-29 01:51 UTC
