### ISSUE TITLE
Access violation on close document

### ISSUE THREAD

**Issue by Iton-Horn** [Dook1/Bookmarks-Dook#23] opened 2022-11-29 00:11 UTC
Hello, dear Notepad++ and Bookmarks-Dook Community!

I would like to report a bug
which occurs under Notepad++ v. 8.4.7 32 bit and Bookmarks-Dook-plugin v. 3.1
as follows.

Steps to reproduce:
1. open a text document,
2. make sure the Bookmarks panel is opened,
3. close the text document using menu [File/Close] or
   by clicking [red close button of the document tab],
4. message appears: "An exception occurred due to plugin: BookmarksDook.dll
                                 Exception reason: Access violation".

Thank you.
Iton

**Comment by Dook1** [comment] 2022-11-29 00:19
I can't reproduce it.

**Comment by Iton-Horn** [comment] 2022-11-29 00:33
Noteped++ is closed. The plugin panel is set up to appear on the right side.
I open a Windows Explorer window and double-click a .txt file containing 12 lines of text.
Notepad++ starts and opens the .txt-file. I close the .txt-file as said and receive the above mentioned message.
![message](https://user-images.githubusercontent.com/91830481/204409401-1651dc69-4c27-4a01-b9de-c5d782fbbd6a.jpg)

**Comment by Dook1** [comment] 2022-11-29 01:43
fixed in 3.1.1
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.1.1

**Closed as completed** 2022-11-29 11:06 UTC
